server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    root /var/www/modengy;
    index index.html;
    location = / { return 302 /promo/dvs/; }
    location / { try_files $uri $uri/ =404; }
}
